### PR TITLE
changed the name of the button to post anonymously

### LINKED ISSUE #9: Implement a front end button that allows you to select anonymous when sending comments & feedback, discussion and announcements
This issue addresses the post anonymously in specific forums user story and will be completed in Sprint 1, with moderate impact and moderate to low difficulty. It involves implementing a front-end button that allows users to select the "anonymous" option when posting in the "Comments & Feedback," "Discussion," and "Announcement" sections. The button should be visible and fully functional for users in these areas. User story is issue #15

### LINKED ISSUE #15: User Story 4: As a user, I want the option to post anonymously in specific forums or threads, so that I can share information or opinions without revealing my identity.

### PR DESCRIPTION
**Pull request by tatougueye**
I just changed the name of the submit anonymous button to make it more coordinated with the other naming conventions in the NodeBB website.

### CODE REVIEW

**Review by aattiyah — CHANGES_REQUESTED** [review]
Changes look good. But I think you can remove the dump.rdb file.

**Review by aattiyah — APPROVED** [review]
Looks good to me

**Review by mohamed-elzeni — APPROVED** [review]
LGTM! Just resolve the dump.rdb conflicts.

**Comment by tatougueye** [comment]
Okay, thank for the feddback. I removed the dump.rdb file.

**Pull request merged**
