### PR TITLE
added front end button to submit anonymously (User Story 4)

### LINKED ISSUE #9: Implement a front end button that allows you to select anonymous when sending comments & feedback, discussion and announcements
This issue addresses the post anonymously in specific forums user story and will be completed in Sprint 1, with moderate impact and moderate to low difficulty. It involves implementing a front-end button that allows users to select the "anonymous" option when posting in the "Comments & Feedback," "Discussion," and "Announcement" sections. The button should be visible and fully functional for users in these areas. User story is issue #15

### LINKED ISSUE #15: User Story 4: As a user, I want the option to post anonymously in specific forums or threads, so that I can share information or opinions without revealing my identity.

### PR DESCRIPTION
**Pull request by tatougueye**
This pull request adds a "Post Anonymously" option to the composer submit dropdown, allowing users to submit their posts anonymously. The option is added as a new list item within the submitOptions dropdown in the composer action bar.  The file that has been modified is nodeBB/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl. This resolves #9.

### CODE REVIEW

**Comment by tatougueye** [comment]
changes are showing now after updating git ignore!

**Review by aattiyah — COMMENTED** [review]
Button is added in node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl. Follows the style of other code and is clear and cleanly written.

**Review by mohamed-elzeni — COMMENTED** [review]
LGTM! I think we can remove dump.rdb after we merge all changes for this sprint.

**Comment by tatougueye** [comment]
Okay glad that it's good. I accidentally clicked merged before the approvals but its good that there are no edits needed to be made.

**Pull request merged**
