### PR TITLE
Add backend logic for posting anonymously (User Story 4)

### LINKED ISSUE #10: Update the database and logic backend to record the value of sender as ‘anonymous’
This issue addresses the post anonymously in specific forums user story and will be completed in Sprint 1, with moderate impact and moderate to low difficulty. It involves updating the backend and database to correctly record the sender as "anonymous" when this option is selected, ensuring that the proper logic is in place to handle anonymous posts efficiently. User story is issue #15

### LINKED ISSUE #11: Make the front end button ‘send as anonymous’ trigger the back end when it is selected by the user
This issue addresses the post anonymously in specific forums user story and will be completed in Sprint 1, with moderate impact and moderate to low difficulty. It involves ensuring that when users select the "send as anonymous" button on the front end, it correctly triggers the backend logic to submit posts anonymously. This guarantees the proper functioning of anonymous submissions across the platform. User story is issue #15

### LINKED ISSUE #15: User Story 4: As a user, I want the option to post anonymously in specific forums or threads, so that I can share information or opinions without revealing my identity.

### PR DESCRIPTION
**Pull request by mohamed-elzeni**
This adds the backend logic of posting anonymously.

It is done by capturing the click of the added "Submit Anonymously" button in the submit dropdown menu and adding an attribute that is passed to the post function. The post function then utilizes `Topics.post` to post as a guest by changing the user ID to 0, making the author of the post completely anonymous.

This has been tested by the linting and testing suite, in addition to testing the interface manually.

The main changes are in the following files:
- `node_modules/nodebb-plugin-composer-default/static/lib/composer.js`
- `node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl`
- `src/topics/create.js`

This resolves #10 & resolves #11. This also fully completes and resolves #15.

### CODE REVIEW

**Comment by tatougueye** [comment]
This looks good to me. I pulled it and its incorporating well with the changes I made!

**Review by tatougueye — APPROVED** [review]
This looks good to me. I pulled it and its incorporating well with the changes I made!

**Review by aattiyah — APPROVED** [review]
The code looks good to me!

**Comment by akobaidan** [comment]
LGTM!

**Review by akobaidan — APPROVED** [review]
LGTM

**Pull request merged**
